### ISSUE TITLE
Is Google Cloud SQL supported?

### ISSUE THREAD

**Issue by rvora** [movetokube/postgres-operator#63]
Hi

I was looking for this exact functionality but so far I don't see instructions for using this operator with Cloud SQL Postgres instance.

Has anyone tried it? I am willing to but I need some pointers on how to get started.

Thanks.

**Comment by arnarg** [comment]
Isn't Google Cloud SQL a bit unique in that the Google cloud SDK supports the functionality of postgres-operator already?

You can create a database and user using terraform for example.

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_database
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_user

**Comment by rvora** [comment]
Yes you can use Cloud SQL API / gcloud command / terraform / etc. to create databases and users. However, this is not Kubernetes Native using CRDs which makes it easy to implement a GitOps-style workflow to manage databases and users.

There is also the Google Config Connector operator but that one lacks some of the features of this operator like creating reader / writer roles automatically and applying default privileges.

BTW, I was able to connect Google Cloud SQL instance using an internal IP address, username and password so I am unblocked. I do not need the External IP connectivity using GCP Service Account, etc.

Howerver, in order to take-over the management of existing Databases with Public schemas I need this pull request to be merged https://github.com/movetokube/postgres-operator/pull/58.

**Comment by hitman99** [comment]
> Howerver, in order to take-over the management of existing Databases with Public schemas I need this pull request to be merged #58.

Unfortunately, that PR was closed without merging the code. That PR is not acceptable the way it was implemented, merging that code would compromise and probably break the permission system that is already in place. We've discussed on how this change could be implemented, if still needed #58 PR. Since you found a solution of connecting to the GCP provided managed postgres, I'm closing this issue as no further Google Cloud SQL specific support is requested.
